# Generated by Django 4.2.23 on 2025-06-27 11:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quotes', '0004_remove_quote_lock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='nbr_call',
            new_name='call_count',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='potentiel',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='score',
        ),
        migrations.AddField(
            model_name='quote',
            name='idEtablissement',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='reference_id_SI',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='weeknumber',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='reference_id_SI',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quoteuserlog',
            name='quote',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_logs', to='quotes.quote'),
        ),
        migrations.AlterField(
            model_name='quoteuserlog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
