# Generated by Django 4.2.23 on 2025-07-11 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0007_remove_quotelock_expireat_quotelock_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotelock',
            name='quote',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lock', to='quotes.quote'),
        ),
    ]
