# Generated by Django 4.2.23 on 2025-07-11 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0008_alter_quotelock_quote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoteuserlog',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('retrieved', 'Retrieved'), ('deleted', 'Deleted'), ('locked', 'Locked'), ('unlocked', 'Unlocked')], max_length=100),
        ),
    ]
