services:
  nginx:
    environment:
      - VIRTUAL_HOST=preprod.qualilead.options.net
    volumes:
      - ./compose/preprod/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./compose/preprod/nginx/.htpasswd:/etc/nginx/.htpasswd

  certbot:
    environment:
      - HOST_PROD=preprod.qualilead.options.net
      - EMAIL_ADMIN=admin.web@options.net