# Generated by Django 4.2.23 on 2025-06-25 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_question_quote_status_reponse_quoteuserlog_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='status',
        ),
        migrations.RemoveField(
            model_name='quoteuserlog',
            name='quote',
        ),
        migrations.RemoveField(
            model_name='quoteuserlog',
            name='user',
        ),
        migrations.RemoveField(
            model_name='reponse',
            name='question',
        ),
        migrations.RemoveField(
            model_name='reponse',
            name='quote',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Quote',
        ),
        migrations.DeleteModel(
            name='QuoteUserLog',
        ),
        migrations.DeleteModel(
            name='Reponse',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
