# Generated by Django 4.2.23 on 2025-07-10 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_quote_status_remove_quoteuserlog_quote_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_create_acceor_user', 'Can create Acceor user'), ('can_create_acceor_admin', 'Can create Acceor Admin'), ('can_create_options_user', 'Can create Options user'), ('can_create_options_admin', 'Can create Options admin')]},
        ),
    ]
