# Generated by Django 4.2.23 on 2025-07-23 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_create_acceor_user', 'Can create Acceor user'), ('can_create_acceor_admin', 'Can create Acceor Admin'), ('can_create_options_user', 'Can create Options user'), ('can_create_options_admin', 'Can create Options admin'), ('can_delete_options_user', 'Can delete Options User'), ('can_delete_acceor_user', 'Can delete Acceor user'), ('can_delete_options_admin', 'Can delete Options admin'), ('can_delete_acceor_admin', 'Can delete Acceor admin'), ('can_view_created_users', 'Can view created users'), ('can_change_user_data', 'Can change user data')]},
        ),
    ]
