# Generated by Django 4.2.23 on 2025-06-27 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0004_alter_givenanswer_answer_alter_givenanswer_question_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reponse',
            name='Questionnaire',
        ),
        migrations.AlterField(
            model_name='givenanswer',
            name='answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='questionnaire.reponse'),
        ),
        migrations.AlterField(
            model_name='givenanswer',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='questionnaire.question'),
        ),
        migrations.AlterField(
            model_name='givenanswer',
            name='questionnaire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='given_answers', to='questionnaire.questionnaire'),
        ),
    ]
