# Generated by Django 4.2.23 on 2025-06-27 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0005_remove_reponse_questionnaire_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reponse',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.question'),
        ),
    ]
