# Generated by Django 4.2.23 on 2025-07-09 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0007_reponse_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reponse',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='questionnaire.question'),
        ),
        migrations.AddConstraint(
            model_name='givenanswer',
            constraint=models.UniqueConstraint(fields=('questionnaire', 'question'), name='unique_answer_per_question_per_questionnaire'),
        ),
    ]
