# Generated by Django 4.2.23 on 2025-06-26 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_quotelock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='lock',
        ),
    ]
