# Generated by Django 4.2.23 on 2025-07-07 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0005_rename_nbr_call_quote_call_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoteuserlog',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quoteuserlog',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('retrieved', 'Retrieved'), ('deleted', 'Deleted')], max_length=100),
        ),
    ]
