# Generated by Django 4.2.23 on 2025-07-10 13:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0006_quoteuserlog_details_alter_quoteuserlog_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotelock',
            name='expireAt',
        ),
        migrations.AddField(
            model_name='quotelock',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='quotelock',
            name='expire_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
