# Generated by Django 4.2.23 on 2025-07-24 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0010_alter_comment_quote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='quote',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='quotes.quote'),
        ),
    ]
