# renew_before_expiry = 30 days
version = 2.10.0
archive_dir = /etc/letsencrypt/archive/www.greathire.com
cert = /etc/letsencrypt/live/www.greathire.com/cert.pem
privkey = /etc/letsencrypt/live/www.greathire.com/privkey.pem
chain = /etc/letsencrypt/live/www.greathire.com/chain.pem
fullchain = /etc/letsencrypt/live/www.greathire.com/fullchain.pem

# Options used in the renewal process
[renewalparams]
account = 6947ffeb2dff50a3651072a4db65fab3
authenticator = webroot
webroot_path = /var/www/certbot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
greathire.com = /var/www/certbot
www.greathire.com = /var/www/certbot
