# Generated by Django 4.2.23 on 2025-06-27 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0002_remove_reponse_quote_questionnaire_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionnaire',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='question',
            name='reference_id_SI',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reponse',
            name='reference_id_SI',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='potential',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='GivenAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='questionnaire.reponse')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='questionnaire.question')),
                ('questionnaire', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='given_answers', to='questionnaire.questionnaire')),
            ],
        ),
    ]
