# Generated by Django 4.2.23 on 2025-06-27 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0005_rename_nbr_call_quote_call_count_and_more'),
        ('questionnaire', '0003_remove_questionnaire_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='givenanswer',
            name='answer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='questionnaire.reponse'),
        ),
        migrations.AlterField(
            model_name='givenanswer',
            name='question',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='questionnaire.question'),
        ),
        migrations.AlterField(
            model_name='givenanswer',
            name='questionnaire',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='given_answers', to='questionnaire.questionnaire'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='quote',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire', to='quotes.quote'),
        ),
    ]
