# Generated by Django 4.2.23 on 2025-06-27 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0006_alter_reponse_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='reponse',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
