# Generated by Django 4.2.23 on 2025-07-10 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0008_alter_reponse_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='order',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
