# Generated by Django 4.2.23 on 2025-07-16 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0010_alter_question_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='givenanswer',
            name='date_answer',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='is_date_input',
            field=models.BooleanField(default=False),
        ),
    ]
