# Generated by Django 4.2.23 on 2025-07-16 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0011_givenanswer_date_answer_question_is_date_input'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='givenanswer',
            name='date_answer',
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='date_prevue',
            field=models.DateField(blank=True, null=True),
        ),
    ]
