# Generated by Django 4.2.23 on 2025-07-23 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0012_remove_givenanswer_date_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='reference_id_SI',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
